/**
 * @license MIT
 * @origin Machine-First Design Agent Wiki
 * @author Machine-First Design Team
 * @curated-by Machine-First Design Agent Wiki
 * DTCG Token Compiler:
 * Reads design-tokens.json (W3C DTCG standard) and compiles:
 * 1. TypeScript typed constants in packages/registry/src/lib/tokens.ts
 * 2. Synchronized token documentation
 */

import fs from "fs";
import path from "path";

interface TokenItem {
  $value: string | number;
  $type?: string;
  $description?: string;
}

interface DesignTokensManifest {
  color?: Record<string, TokenItem>;
  radius?: Record<string, TokenItem>;
  spacing?: Record<string, TokenItem>;
  motion?: {
    spring?: Record<string, TokenItem>;
    duration?: Record<string, TokenItem>;
  };
}

export function compileTokens() {
  console.log("🎨 Compiling W3C DTCG Design Tokens...");

  const tokensFile = path.resolve(__dirname, "design-tokens.json");
  if (!fs.existsSync(tokensFile)) {
    console.error(`❌ Token source not found: ${tokensFile}`);
    process.exit(1);
  }

  const rawJson = fs.readFileSync(tokensFile, "utf-8");
  const manifest: DesignTokensManifest = JSON.parse(rawJson);

  // Generate TypeScript Definitions
  let tsOutput = `/**
 * @license MIT
 * @origin Machine-First Design Agent Wiki (DTCG Standard)
 * @author Machine-First Design Team
 * @curated-by Machine-First Design Agent Wiki
 * Auto-generated by build-tokens.ts from packages/registry/tokens/design-tokens.json
 * Do not edit manually.
 */

export const DESIGN_TOKENS = {
  colors: {
`;

  if (manifest.color) {
    for (const [key, item] of Object.entries(manifest.color)) {
      tsOutput += `    /** ${item.$description || key} */\n`;
      tsOutput += `    ${key}: "${item.$value}",\n`;
    }
  }

  tsOutput += `  },\n  radii: {\n`;
  if (manifest.radius) {
    for (const [key, item] of Object.entries(manifest.radius)) {
      tsOutput += `    ${key}: "${item.$value}",\n`;
    }
  }

  tsOutput += `  },\n  spacing: {\n`;
  if (manifest.spacing) {
    for (const [key, item] of Object.entries(manifest.spacing)) {
      tsOutput += `    "${key}": "${item.$value}",\n`;
    }
  }

  tsOutput += `  },\n  motion: {\n    spring: {\n`;
  if (manifest.motion?.spring) {
    for (const [key, item] of Object.entries(manifest.motion.spring)) {
      tsOutput += `      ${key}: ${item.$value},\n`;
    }
  }
  tsOutput += `    },\n    duration: {\n`;
  if (manifest.motion?.duration) {
    for (const [key, item] of Object.entries(manifest.motion.duration)) {
      tsOutput += `      ${key}: "${item.$value}",\n`;
    }
  }
  tsOutput += `    },\n  },\n} as const;\n\n`;
  tsOutput += `export type DesignTokens = typeof DESIGN_TOKENS;\n`;

  const tsDest = path.resolve(__dirname, "../src/lib/tokens.ts");
  fs.mkdirSync(path.dirname(tsDest), { recursive: true });
  fs.writeFileSync(tsDest, tsOutput, "utf-8");
  console.log(`  ✓ Generated TypeScript Token Constants: ${tsDest}`);

  console.log("🎉 DTCG Design Tokens successfully compiled!");
}

if (require.main === module) {
  compileTokens();
}
