/**
 * @license MIT
 * @origin Machine-First Design Agent Wiki (DTCG Standard)
 * @author Machine-First Design Team
 * @curated-by Machine-First Design Agent Wiki
 * Auto-generated by build-tokens.ts from packages/registry/tokens/design-tokens.json
 * Do not edit manually.
 */

export const DESIGN_TOKENS = {
  colors: {
    /** Root page background canvas */
    background: "hsl(0 0% 100%)",
    /** Default text and icon foreground */
    foreground: "hsl(240 10% 3.9%)",
    /** Structured card background surface */
    card: "hsl(0 0% 100%)",
    /** Card content foreground text */
    cardForeground: "hsl(240 10% 3.9%)",
    /** Primary action and high-emphasis accent */
    primary: "hsl(240 5.9% 10%)",
    /** Text rendered over primary surface */
    primaryForeground: "hsl(0 0% 98%)",
    /** Secondary surface for subdued cards and badges */
    secondary: "hsl(240 4.8% 95.9%)",
    /** Text rendered over secondary surface */
    secondaryForeground: "hsl(240 5.9% 10%)",
    /** Muted backgrounds and subtle highlights */
    muted: "hsl(240 4.8% 95.9%)",
    /** Subdued secondary text meeting WCAG AA contrast */
    mutedForeground: "hsl(240 3.8% 46.1%)",
    /** Interactive hover and selected accent */
    accent: "hsl(240 4.8% 95.9%)",
    /** Foreground on interactive accent */
    accentForeground: "hsl(240 5.9% 10%)",
    /** Destructive and error state indicators */
    destructive: "hsl(0 84.2% 60.2%)",
    /** Text rendered over destructive surface */
    destructiveForeground: "hsl(0 0% 98%)",
    /** Hairline structural border divider */
    border: "hsl(240 5.9% 90%)",
    /** Form input and toggle border token */
    input: "hsl(240 5.9% 90%)",
    /** Accessible focus-visible ring indicator */
    ring: "hsl(240 5.9% 10%)",
  },
  radii: {
    sm: "0.375rem",
    md: "0.5rem",
    lg: "0.75rem",
    xl: "1rem",
  },
  spacing: {
    "1": "0.25rem",
    "2": "0.5rem",
    "3": "0.75rem",
    "4": "1rem",
    "6": "1.5rem",
    "8": "2rem",
    "12": "3rem",
    "16": "4rem",
  },
  motion: {
    spring: {
      stiffness: 300,
      damping: 28,
      mass: 0.9,
    },
    duration: {
      fast: "150ms",
      normal: "200ms",
      deliberate: "350ms",
    },
  },
} as const;

export type DesignTokens = typeof DESIGN_TOKENS;
