import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

export const dynamic = "force-static";

export async function GET() {
  const filePath = path.resolve(process.cwd(), "public/llms.txt");

  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, "utf-8");
    return new NextResponse(content, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": "public, max-age=3600, s-maxage=86400",
      },
    });
  }

  // Fallback if public/llms.txt not yet generated by compiler
  const fallback = `# Machine-First Design Agent Wiki
> Grounding AI coding agents in deterministic, zero-slop UI primitives.

## Machine Discovery Endpoints
- Registry Manifest: /r/registry.json
- LLMs Full Context: /llms-full.txt
- Raw Markdown Stream: /raw/components/[slug]
- Model Context Protocol: npx @design-wiki/mcp

Run 'pnpm run build:registry' to compile full registry item listings.
`;

  return new NextResponse(fallback, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
